#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	# On GameCube, menu stub is built as part of the engine
	# This wscript is only for other platforms that might need a separate menu stub
	if bld.env.DEST_OS == 'gamecube':
		return

	bld.shlib(
		source = bld.path.ant_glob('*.c'),
		target = 'menu',
		includes = ['.', '../../engine', '../../engine/common', '../../engine/client', '../../engine/platform', '../../public'],
		defines = ['ENGINE_DLL=1'],
		use = ['engine_includes', 'public', 'werror'],
		install_path = bld.env.LIBDIR,
	)
