#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	if bld.env.DEST_OS != 'gamecube':
		return

	bld.stlib(
		source = bld.path.ant_glob('*.c'),
		target = 'client_stub',
		includes = ['../../engine', '../../engine/common', '../../engine/client', '../../engine/platform/gamecube', '../../public'],
		use = ['engine_includes', 'public', 'werror'],
		install_path = bld.env.LIBDIR,
	)
