#!/usr/bin/env python3
"""Extract line-bounded excerpts from large repo files for Aider read-only context."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


def parse_ranges(spec: str) -> list[tuple[int, int]]:
	ranges: list[tuple[int, int]] = []
	for chunk in spec.split(","):
		chunk = chunk.strip()
		if not chunk:
			continue
		if "-" not in chunk:
			raise ValueError(f"invalid range {chunk!r}; expected START-END")
		start_s, end_s = chunk.split("-", 1)
		start = int(start_s)
		end = int(end_s)
		if start < 1 or end < start:
			raise ValueError(f"invalid range {chunk!r}")
		ranges.append((start, end))
	if not ranges:
		raise ValueError("no ranges provided")
	return ranges


def slice_text(source: Path, ranges: list[tuple[int, int]]) -> str:
	lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
	parts: list[str] = [
		f"# Slice of {source.as_posix()} for automation context (do not edit this file)",
		"# Apply edits to the real source path named above.",
		"",
	]
	for start, end in ranges:
		if start > len(lines):
			continue
		clip_end = min(end, len(lines))
		parts.append(f"# --- lines {start}-{clip_end} ---")
		for lineno in range(start, clip_end + 1):
			parts.append(f"{lineno:5d}|{lines[lineno - 1]}")
		parts.append("")
	return "\n".join(parts).rstrip() + "\n"


def slice_path(source: Path, ranges: list[tuple[int, int]], output: Path) -> Path:
	output.parent.mkdir(parents=True, exist_ok=True)
	content = slice_text(source, ranges)
	output.write_text(content, encoding="utf-8")
	return output


def default_output_path(source: Path, ranges: list[tuple[int, int]]) -> Path:
	digest = hashlib.sha1(
		source.as_posix().encode() + repr(ranges).encode()
	).hexdigest()[:10]
	name = f"{source.name}.{digest}.slice"
	return Path(".ai/slices") / source.parent / name


def main() -> int:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--source", type=Path, required=True)
	parser.add_argument("--ranges", required=True, help="comma-separated START-END ranges")
	parser.add_argument("--output", type=Path, default=None)
	args = parser.parse_args()

	source = args.source
	if not source.is_file():
		print(f"aider-context-slice: missing source: {source}", file=sys.stderr)
		return 1

	ranges = parse_ranges(args.ranges)
	output = args.output or default_output_path(source, ranges)
	slice_path(source, ranges, output)
	print(output.as_posix())
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
