#!/usr/bin/env python3
"""Generate GameCube static exports for HLSDK functions."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser()
	parser.add_argument("--archive", required=True, type=Path)
	parser.add_argument("--output", required=True, type=Path)
	parser.add_argument("--symbol-name", default="lib_hl_gamecube_ppc_exports", help="Symbol name for the exports array")
	parser.add_argument("--nm", default=os.environ.get("NM"))
	return parser.parse_args()


def nm_tool(args: argparse.Namespace) -> str:
	if args.nm:
		return args.nm
	devkitpro = os.environ.get("DEVKITPRO", "/opt/devkitpro")
	return str(Path(devkitpro) / "devkitPPC" / "bin" / "powerpc-eabi-nm")


def archive_symbols(nm: str, archive: Path) -> set[str]:
	result = subprocess.run(
		[nm, "-g", "--defined-only", str(archive)],
		check=True,
		text=True,
		stdout=subprocess.PIPE,
	)
	symbols: set[str] = set()
	for line in result.stdout.splitlines():
		fields = line.split()
		if len(fields) >= 3 and len(fields[2]) > 0:
			symbols.add(fields[2])
	return symbols


def write_output(output: Path, symbols: set[str], symbol_name: str) -> None:
	output.parent.mkdir(parents=True, exist_ok=True)
	
	# Filter for the functions we need
	required_functions = {
		"GetEntityAPI",
		"GetEntityAPI2",
		"GiveFnptrsToDll",
		"GetNewDLLFunctions",
		"CreateInterface",
		"GetFSAPI",
	}
	
	# Find the symbols that match our required functions
	found_symbols = {s for s in symbols if s in required_functions}
	
	# Generate the dllexport_t array
	lines = [
		"/* Auto-generated by scripts/generate-gamecube-exports.py. */",
		"/* Do not edit this file directly. */",
		"",
		"#include \"common.h\"",
		"#include \"library.h\"",
		"",
	]
	
	# Generate extern declarations for each symbol
	for sym in sorted(found_symbols):
		lines.append(f"extern void {sym}(void);")
	
	lines.append("")
	
	# Generate the dllexport_t array
	lines.append(f"dllexport_t {symbol_name}[] = {{")
	for sym in sorted(found_symbols):
		lines.append(f'	{{ "{sym}", (void *){sym} }},')
	lines.append("	{ NULL, NULL },")
	lines.append("};")
	lines.append("")
	
	# Write the output
	output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
	args = parse_args()
	
	if not args.archive.is_file():
		print(f"generate: missing archive: {args.archive}", file=sys.stderr)
		return 2
	
	symbols = archive_symbols(nm_tool(args), args.archive)
	
	if not symbols:
		print("generate: no symbols found in archive", file=sys.stderr)
		return 3
	
	write_output(args.output, symbols, args.symbol_name)
	print(f"Generated GameCube exports: {args.output}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
