#!/usr/bin/env python3
"""Generate GameCube static exports for HLSDK entity class functions."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


ENTITY_RE = re.compile(r"\bLINK_ENTITY_TO_CLASS\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,")
SYMBOL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser()
	parser.add_argument("--hlsdk-dir", required=True, type=Path)
	parser.add_argument("--archive", required=True, type=Path)
	parser.add_argument("--output", required=True, type=Path)
	parser.add_argument("--nm", default=os.environ.get("NM"))
	return parser.parse_args()


def nm_tool(args: argparse.Namespace) -> str:
	if args.nm:
		return args.nm
	devkitpro = os.environ.get("DEVKITPRO", "/opt/devkitpro")
	return str(Path(devkitpro) / "devkitPPC" / "bin" / "powerpc-eabi-nm")


def archive_symbols(nm: str, archive: Path) -> set[str]:
	result = subprocess.run(
		[nm, "-g", "--defined-only", str(archive)],
		check=True,
		text=True,
		stdout=subprocess.PIPE,
	)
	symbols: set[str] = set()
	for line in result.stdout.splitlines():
		fields = line.split()
		if len(fields) >= 3 and SYMBOL_RE.match(fields[2]):
			symbols.add(fields[2])
	return symbols


def strip_comments(text: str) -> str:
	out: list[str] = []
	i = 0
	length = len(text)
	while i < length:
		if text.startswith("//", i):
			while i < length and text[i] != "\n":
				i += 1
			if i < length:
				out.append(text[i])
				i += 1
		elif text.startswith("/*", i):
			i += 2
			while i < length and not text.startswith("*/", i):
				if text[i] == "\n":
					out.append("\n")
				i += 1
			if i < length:
				i += 2
		else:
			out.append(text[i])
			i += 1
	return "".join(out)


def entity_names(hlsdk_dir: Path) -> list[str]:
	dlls = hlsdk_dir / "dlls"
	if not dlls.is_dir():
		raise SystemExit(f"generate: missing HLSDK dlls directory: {dlls}")

	names: set[str] = set()
	for path in sorted(dlls.rglob("*")):
		if path.suffix.lower() not in {".c", ".cc", ".cpp", ".h", ".hpp"}:
			continue
		text = strip_comments(path.read_text(encoding="utf-8", errors="ignore"))
		names.update(match.group(1) for match in ENTITY_RE.finditer(text))
	return sorted(names)


def write_output(output: Path, names: list[str]) -> None:
	output.parent.mkdir(parents=True, exist_ok=True)
	lines = [
		"/* Auto-generated by scripts/generate-hlsdk-gamecube-exports.py. */",
		"/* Regenerate from the external hlsdk-portable checkout; do not edit. */",
		"#ifndef GAMECUBE_SERVER_ENTITY",
		"#error GAMECUBE_SERVER_ENTITY must be defined before including this file",
		"#endif",
		"",
	]
	lines.extend(f"GAMECUBE_SERVER_ENTITY({name})" for name in names)
	lines.append("")
	output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
	args = parse_args()
	if not args.archive.is_file():
		print(f"generate: missing server archive: {args.archive}", file=sys.stderr)
		return 2

	symbols = archive_symbols(nm_tool(args), args.archive)
	source_names = entity_names(args.hlsdk_dir)
	names = [name for name in source_names if name in symbols]
	missing = [name for name in source_names if name not in symbols]

	if not names:
		print("generate: no HLSDK entity symbols found in archive", file=sys.stderr)
		return 3

	write_output(args.output, names)
	print(f"Generated {len(names)} GameCube HLSDK entity exports: {args.output}")
	if missing:
		print(f"Skipped {len(missing)} source entities absent from archive", file=sys.stderr)
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
